const MenuList = [
  {
    name: "Dashboard",
    icon: "dashboard",
    alias: "dashboard",
    isHide: false,
    route: "/dashboard",
    child: [],
  },
  {
    name: "Tagihan",
    icon: "bill",
    alias: "bill",
    isHide: false,
    route: "",
    child: [
      {
        name: "List tagihan",
        route: "/bill",
        alias: "listBill",
        child: [],
        isHide: false,
      },
      {
        name: "Daftar IPL",
        route: "",
        alias: "listIpl",
        child: [],
        isHide: false,
      },
      {
        name: "Pengaturan IPL",
        route: "",
        alias: "settingIpl",
        child: [],
        isHide: false,
      },
    ],
  },
  {
    name: "Papan Info",
    icon: "info",
    alias: "info",
    isHide: false,
    route: "",
    child: [
      {
        name: "List Info",
        route: "/info",
        alias: "listInfo",
        child: [],
        isHide: false,
      },
      {
        name: "Pelanggan",
        route: "",
        alias: "customerInfo",
        child: [],
        isHide: false,
      },
      {
        name: "Petugas",
        route: "",
        alias: "employeeInfo",
        child: [],
        isHide: false,
      },
    ],
  },
  {
    name: "Email / SMS",
    icon: "email",
    alias: "email",
    isHide: false,
    route: "/mail",
    child: [],
  },
  {
    name: "Info Penyewa",
    icon: "tenant",
    alias: "tenant",
    isHide: false,
    route: "/chart",
    child: [],
  },
  {
    name: "Info Karyawan",
    icon: "employee",
    alias: "employee",
    isHide: false,
    route: "",
    child: [],
  },
  {
    name: "Jadwasl Shift",
    icon: "shift",
    alias: "shift",
    isHide: false,
    route: "",
    child: [],
  },
  {
    name: "Parkir",
    icon: "parking",
    alias: "parking",
    isHide: false,
    route: "",
    child: [],
  },
  {
    name: "Keluhan",
    icon: "complaint",
    alias: "complaint",
    isHide: false,
    route: "",
    child: [],
  },
];

export default MenuList;
