env:
  browser: true
  es2021: true
  jest: true
  node: true
extends:
  - react-app
  - react-app/jest
  - plugin:react/recommended
  - airbnb
  - plugin:prettier/recommended
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - prettier
settings:
  import/resolver:
    node:
      extensions:
        - ".ts"
        - ".tsx"
        - ".js"
        - ".jsx"
      moduleDirectory:
        - src
        - node_modules
rules:
  quotes:
    - error
    - double
    - avoidEscape: true
  react/jsx-uses-react: 'off'
  react/react-in-jsx-scope: 'off'
  react/jsx-props-no-spreading: 'off'
  no-shadow: 'off'
  prettier/prettier:
    - error
    - endOfLine: auto
  global-require: 0
  jsx-a11y/label-has-associated-control:
    - error
    - required:
        some:
          - nesting
          - id
  jsx-a11y/label-has-for:
    - error
    - required:
        some:
          - nesting
          - id
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true
      optionalDependencies: false
      peerDependencies: false
  react/forbid-prop-types: off
  react/void-dom-elements-no-children: off
  react/jsx-no-bind: off
